<!-- START of: finna - RecordDriver/SolrLrmi/core.phtml -->
<?php
  $rights = $this->driver->getAccessRestrictionsType($this->layout()->userLang);
  $summary = $this->driver->getSummary();
  $aoeLink = $this->driver->getExternalLink();
  $materials = $this->driver->getMaterials($this->layout()->userLang);
  $dateCreated = $this->driver->getDateCreated();
  $dateModified = $this->driver->getDateModified();
  $img = $this->recordImage($this->record($this->driver));
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
  $formats = $this->driver->getFormats();
  ob_start(); ?>
  <div class="media-<?=$thumbnailAlignment?>">
    <?=$this->record($this->driver)->renderTemplate('record-image-information.phtml', ['img' => $img, 'displayIcon' => true, 'source' => 'L1', 'imageClick' => 'none']);?>
    <?=$this->record($this->driver)->renderTemplate('record-post-thumbnail.phtml');?>
  </div>
  <?php $thumbnail = ob_get_contents(); ?>
<?php ob_end_clean(); ?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <h1 property="name" class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getShortTitle())?><?php if ($subtitle = $this->driver->getSubtitle()): ?>&nbsp;: <?=$this->escapeHtml($subtitle) ?><?php endif; ?></h1>
  <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
  <div class="media-body record-information">
    <h1 property="name" class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getShortTitle())?><?php if ($subtitle = $this->driver->getSubtitle()): ?>&nbsp;: <?=$this->escapeHtml($subtitle) ?><?php endif; ?></h1>
    <?php if (!empty($formats)): ?>
      <span class="recordFormat"><?=$this->record($this->driver)->getFormatList()?></span>
    <?php endif; ?>
    <div class="record-core-metadata">
      <?php if ($results = $this->driver->getNonPresenterAuthors()): ?>
        <div class="truncate-field recordAuthors">
          <span property="author">
            <?php foreach($results as $index => $author): ?>
              <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?><?php if (!empty($author['affiliation'])): ?>, <?= $this->escapeHtml($author['affiliation']) ?><?php endif;?></a>
            <?php endforeach; ?>
          </span>
        </div>
        <div class="date-created date-modified">
          <span><?= $dateCreated ? $this->transEsc('Created') . ': ' . $dateCreated : '';?><?= $dateCreated && $dateModified ? ', ' : ''?><?= $dateModified ? $this->transEsc('modified') . ': ' . $dateModified : '';?></span>
        </div>
      <?php endif; ?>
      <?php if ($summary): ?>
        <div class="truncate-field material-description">
          <?= $this->escapeHtml($summary); ?>
        </div>
      <?php endif; ?>
      <?/* Display Main Details */?>
      <?php
        $formatter = $this->recordDataFormatter();
        $filteredFields = $formatter->filterLrmiFields($formatter->getDefaults('core'));
        $coreFields = $formatter->getGroupedData($driver, $formatter->getGroupedFields([], $filteredFields));
      ?>
      <?php if (!empty($coreFields)): ?>
        <table class="table table-finna-record record-details record-details-more record-field-groups">
          <?=$this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $coreFields]);?>
        </table>
        <button class="btn show-details-button hidden"><?=$this->transEsc('show_more_details');?> <i class="fa fa-arrow-down"></i></button>
        <button class="btn hide-details-button hidden"><?=$this->transEsc('show_less_details');?> <i class="fa fa-arrow-up"></i></button>
      <?php endif; ?>
      <?/* End Main Details */?>
      <div class="learning-material">
        <h3><?= $this->transEsc('Contains'); ?></h3>
        <?php if (!empty($materials)): ?>
          <div class="recordURLs local-available-online-record">
            <ul class="truncate-field outer">
              <?php
                $externalLink = $this->escapeHtmlAttr($this->translate('external_online_link'));
                $link = $this->transEsc('link');
                $linkedFormats = ['html', 'avi', 'mp4', 'mp3', 'pdf', 'docx', 'doc', 'odt', 'rtf', 'txt', 'ppt', 'pptx', 'odp', 'm4a', 'png', 'jpeg'];
                $toolTipNoMaterialLink = $this->escapeHtmlAttr(
                  $this->translate('tooltip_aoe_no_material_link_html',
                  ['%%link%%' => '<a href="' . ($aoeLink ?? 'https://aoe.fi') . '" target="_blank">aoe.fi</a>' ])
                );
              ?>
              <?php foreach ($materials as $material): ?>
                <?php $html = $material['format'] === 'html'; ?>
                <li class="fulltextField">
                  <?php if (in_array($material['format'], $linkedFormats)): ?>
                    <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($material['url'])) ?>"
                      aria-label="<?=$externalLink?>" target="_blank"><i class="fa <?= $html ? 'fa-external-link' : 'fa-download' ?>"></i>
                      <?= $this->escapeHtml($material['title']) ?></a>
                      (<?= $html ? $link : $this->escapeHtml($material['format']) ?>)
                  <?php else: ?>
                    <button class="btn-reset" type="button" data-toggle="tooltip"
                      data-placement="bottom" data-original-title="<?= $toolTipNoMaterialLink ?>"
                      data-html="true" aria-label="<?= $this->transEsc('Search Tips') ?>">
                      <i class="fa fa-info3"></i>
                    </button>
                    <?= $this->escapeHtml($material['title']) ?>
                  <?php endif; ?>
                </li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
        <div class="alert-info aoe-alert">
          <p><?= $this->transEsc('material_aoe_disclaimer') ?></p>
          <?php if ($aoeLink): ?>
            <p><a href="<?= $aoeLink ?>" target="_blank" class="btn btn-primary"><?= $this->transEsc('go_to_aoe.fi') ?></a></p>
          <?php endif; ?>
        </div>
        <?php if ($rights): ?>
          <div class="material-rights">
            <h4><?= $this->transEsc('Image Rights') ?></h4>
            <span class="rights-icons">
              <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $rights['copyrights']]);?>
              <span class="material-copyright"><?= $this->escapeHtml($rights['copyrights']); ?></span>
            </span>
            <?php if ($rights['link']): ?>
              <span class="rights-link">
                <a href="<?= $this->escapeHtmlAttr($rights['link']); ?>" target="_blank"><?= $this->transEsc('usage_meaning')?></a>
              </span>
            <?php endif; ?>
          </div>
        <?php endif; ?>
      </div>
    </div>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
      <div>
        <?=$this->render($template)?>
      </div>
    <?php endif; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/SolrLrmi/core.phtml -->
