<!-- START of: finna - myresearch/sortlist.phtml -->
<?php
  $this->assetManager()->appendScriptLink('finna-mylist.js');
  $user = $this->auth()->getUserObject();
  $results = empty($this->sortAllLists)
    ? $this->results->getResults()
    : $this->results;

  // Set up breadcrumbs:
  $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
    ->add($this->translate('Sort manually'), active: true);
?>

<?=$this->component('page-title', ['title' => $this->translate('Sort manually')]);?>

<?=$this->flashmessages()?>
<form method="post" id="sort_form" name="sortForm">
  <input type="hidden" name="user_id" value="<?=$this->escapeHtmlAttr($user->getId()) ?>">
  <?php if (empty($this->sortAllLists)): ?>
    <input type="hidden" name="list_id" value="<?=$this->escapeHtmlAttr($this->results->getListObject()->getId()) ?>">
  <?php endif; ?>
  <input type="hidden" id="orderedList" name="orderedList" value="">

  <div>
    <div class="own-favorite-list-button-area">
      <input id="save_order_btn" name="saveOrdering" type="submit" value="<?=$this->transEscAttr('Save Order') ?>" class="btn btn-primary">
      <input id="cancel_order_btn" name="cancelOrdering" type="submit" data-bs-dismiss="modal" value="<?=$this->transEscAttr('Reset') ?>" class="btn btn-primary">
    </div>
    <div class="clearfix"></div>
  </div>
</form>
<ol id="sortable" class="sortable-favorite-list">
  <?php foreach ($results as $i => $current): ?>
    <?php if (empty($this->sortAllLists)): ?>
      <li id="<?=$this->escapeHtmlAttr($current->getUniqueId()) ?>"><h4><?= $this->escapeHtml($current->getTitle()) ?><?=$this->icon('sort', 'sort-icon') ?></h4><p><?=$this->record($current)->getFormatList() ?></p></li>
    <?php else: ?>
      <li id="<?=$this->escapeHtmlAttr($current['list_entity']->getId()) ?>"><h4><?= $this->escapeHtml($current['list_entity']->getTitle()) ?><?=$this->icon('sort', 'sort-icon') ?></h4><p><?= $this->transEsc('List') ?></p></li>
    <?php endif; ?>
  <?php endforeach; ?>
</ol>

<?php
$script = <<<EOT
    if ($.isReady) {
      finna.myList.initFavoriteOrderingFunctionality();
    } else {
      $(document).ready(function(){
        finna.myList.initFavoriteOrderingFunctionality();
      });
    }
    EOT;

// Inline the script for lightbox compatibility
echo $this->assetManager()->outputInlineScriptString($script);
?>
<!-- END of: finna - myresearch/sortlist.phtml -->

