<!-- START of: finna - feedcontent/content.phtml -->
<?php
  $this->headScript()->appendFile('finna-content-feed.js');
  $this->headTitle($this->translate(''));
  $this->content()->setHeading($this->translate(''));
  $this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
     'content/header.phtml', ['heading' => $this->content()->getHeading()]
  );
  $this->jsTranslations()->addStrings([
    'rss_article_not_found' => 'rss_article_not_found',
    'rss_article_channel_link' => 'rss_article_channel_link'
  ]);

  if ($this->modal) {
     $setupJS = <<<JS
$(document).ready(function() {
   finna.contentFeed.loadFeed($('#modal .feed-content'), true);
});
JS;
    echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $setupJS, 'SET');
  }
?>
<div>
  <div class="<?= $this->modal ? '' : 'page-content'?> feed-content" data-feed="<?=$this->escapeHtmlAttr($this->feed)?>" data-element="<?=$this->escapeHtmlAttr($this->element)?>" data-feed-url="<?=$this->escapeHtmlAttr($this->feedUrl)?>">

  <?php if ($this->modal): ?>
    <div class="date"><?=$this->transEsc('Published');?>: <span></span></div>
    <div class="holder"></div>
  </div>

  <?php else: ?>
    <div>
      <div class="mainbody left">
        <div class="date"><?=$this->transEsc('Published');?>: <span></span></div>
        <div class="xcal row">
          <span class="dtstart hidden"><i class="fa fa-calendar"></i> </span>
          <span class="time hidden"><i class="fa fa-clock-o"></i> </span>
          <span class="location hidden"><i class="fa fa-map-marker"></i> </span>
        </div>
        <div class="featured"></div>
        <div class="row hidden">
          <div class="col-xs-4 col-md-2"><?= $this->transEsc('Date')?></div>
          <div class="col-xs-8 dtstart"></div>
        </div>
        <div class="row hidden">
          <div class="col-xs-4 col-md-2"><?= $this->transEsc('Location')?></div>
          <div class="col-xs-8 location"></div>
        </div>
        <div class="row hidden">
          <div class="col-xs-4 col-md-2"></div>
          <div class="col-xs-8 location-address"></div>
        </div>
        <div class="row hidden">
          <div class="col-xs-4 col-md-2"></div>
          <div class="col-xs-8 location-city"></div>
        </div>
        <div class="row hidden">
          <div class="col-xs-4 col-md-2"><?= $this->transEsc('Organizer')?></div>
          <div class="col-xs-8 organizer"></div>
        </div>
        <div class="row hidden">
          <div class="col-xs-4 col-md-2"><?= $this->transEsc('websites')?></div>
          <div class="col-xs-8 organizer-url"></div>
        </div>
        <div class="row hidden">
          <div class="col-xs-4 col-md-2"><?= $this->transEsc('Cost')?> (€)</div>
          <div class="col-xs-8 cost"></div>
        </div>
        <div class="row hidden">
          <div class="col-xs-4 col-md-2"><?= $this->transEsc('Category')?></div>
          <div class="col-xs-8 categories"></div>
        </div>
        <div class="row hidden">
          <br>
          <div class="col-xs-12 content"></div>
        </div>
        <div class="holder"></div>
      </div>
    </div>
  </div>
  <div class="sidebar right">
    <div><h3 class="article-navigation-header"><?=$this->translate('content-feed-navigation')?></h3></div>
    <div class="article-navigation-wrapper"></div>
  </div>
  <?php endif; ?>

</div>
<!-- END of: finna - feedcontent/content.phtml -->
