<!-- START of: finna - feedcontent/content.phtml -->
<?php
  $this->headScript()->appendFile('finna-content-feed.js');
  $this->headTitle($this->translate(''));
  $this->content()->setHeading($this->translate(''));
  $this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
     'content/header.phtml', ['heading' => $this->content()->getHeading()]
  );
  $this->jsTranslations()->addStrings([
    'rss_article_not_found' => 'rss_article_not_found',
    'rss_article_channel_link' => 'rss_article_channel_link'
  ]);

  if ($this->modal) {
     $setupJS = <<<JS
$(document).ready(function() {
   finna.contentFeed.loadFeed($('#modal .feed-content'), true);
});
JS;
    echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $setupJS, 'SET');
  }
?>
<div>
  <div class="<?= $this->modal ? '' : 'page-content'?> feed-content" data-feed="<?=$this->escapeHtmlAttr($this->feed)?>" data-element="<?=$this->escapeHtmlAttr($this->element)?>" data-feed-url="<?=$this->escapeHtmlAttr($this->feedUrl)?>">

  <?php if (!$this->modal): ?>
    <div class="mainbody left">
  <?php endif ?>
    <div class="date"><?=$this->transEsc('Published');?>: <span></span></div>
    <div class="xcal">
      <span class="xdate hidden"><i class="fa fa-calendar"></i> </span> 
      <span class="time hidden"><i class="fa fa-clock-o"></i> </span>
      <span class="location hidden"><i class="fa fa-map-marker"></i> </span>
    </div>
    <div class="featured"></div>
    <div class="xcal-fields">
      <div class="xdate hidden"><?= $this->transEsc('Date')?></div>
      <div class="location hidden"><?= $this->transEsc('Location')?></div>
      <div class="location-address hidden"><?= $this->transEsc('Address')?></div>
      <div class="location-city hidden"><?= $this->transEsc('City')?></div>
      <div class="organizer hidden"><?= $this->transEsc('Organizer')?></div>
      <div class="organizer-url hidden"><?= $this->transEsc('websites')?></div>
      <div class="cost hidden"><?= $this->transEsc('Cost')?></div>
    </div>
    <div class="holder"></div>
  <?php if (!$this->modal): ?>
    </div>
  </div>
    <div class="sidebar right">
      <div><h3 class="article-navigation-header"><?=$this->translate('content-feed-navigation')?></h3></div>
      <div class="article-navigation-wrapper"></div>
    </div>
  <?php endif; ?>

</div>
<!-- END of: finna - feedcontent/content.phtml -->
