<!-- START of: finna - myresearch/paljo-account-creation.phtml -->
<h1><?=$this->transEsc('Kuvatilaustunnus')?></h1>
<div class="infobox">
  <p>Finna-tiliisi ei ole liitetty kuvatilaustunnusta. Tämä kuvatilaus käsitellään PALJO-kuvatilausjärjestelmässä. Luo liitos täydentämällä oheiset tiedot</p>
</div>
<div>
  <p><b><?=$this->transEsc('Email')?></b></p>
  <input type="text">
</div>

<!-- END of: finna - myresearch/paljo-account-creation.phtml -->
