<?php
  $user = $this->auth()->isLoggedIn();
  $imageSize = $this->driver->tryMethod('getPaljoImageSize');
  $images = $this->driver->getAllImages();
?>
<h1><?=$this->transEsc('paljo_image_subscription')?> <i class="fa fa-info-big"></i></h1>
<div class="infobox"><?=$this->transEsc('paljo_image_subscription_info')?></div>
<div><?=$this->transEsc('paljo_user_email')?> <b><span class="paljo-user-email"><?=$user->getPaljoId()?></span></b></div>
<div class="paljo-sub-container">
  <div class="paljo-image">
    <img src="<?= $images[0]['urls']['medium'] ?>" />
  </div>
  <form id="paljo-form" action="<?=$this->url('paljo-payment')?>" method="post">
    <div class="paljo-image-info-container">
      <div class="paljo-image-id">
        <input type="hidden" name="image-id" value="<?=$this->id?>" />
        <b><span class="paljo-image-info"><?=$this->transEsc('paljo_image_id')?></span></b> <span><?=$this->id?></span>
      </div>
      <div class="paljo-price-type">
        <b><span class="paljo-image-info"><?=$this->transEsc('paljo_price_type')?></span></b>
        <select class="paljo-price-type-menu" id="paljo-price-menu" name="paljo-price-type">
          <?php foreach ($this->prices['price'] as $type => $price): ?>
            <option class="paljo-price-type" value="<?= $this->escapeHtmlAttr($price)?>" data-license="<?=$this->escapeHtmlAttr()?>"><?=$type?></option>
          <?php endforeach; ?>
        </select>
      </div>
      <?php if (!empty($imageSize)): ?>
        <div class="paljo-image-size">
          <b><span class="paljo-image-info"><?=$this->transEsc('paljo_image_size')?></span></b>
            <?=$imageSize['height']['value']?> * <?=$imageSize['width']['value']?> <?=$imageSize['width']['unit']?> (<?php //=$imageSize['type']['value']?>)
        </div>
      <?php endif; ?>
      <div class="paljo-license">
        <input type="hidden" name="license" value="" />
        <b><span class="paljo-image-info"><?=$this->transEsc('paljo_license')?>: </span></b> <span class="paljo-image-license"></span>
      </div>
      <div>
        <b><span class="paljo-image-info"><?=$this->transEsc('paljo_additional_information')?></span></b>
        <textarea class="paljo-additional-info" type="text" name="additionalInfo" rows="3" cols="20"></textarea>
      </div>
      <div>
        <b><span class="paljo-volume"><?=$this->transEsc('paljo_volume_code')?></span></b>
        <input type="text" name="volume-code" class="paljo-volume-code" placeholder="<?=$this->escapeHtmlAttr($this->translate('Input'))?>"><button class="discount btn btn-primary"> hae alennus</button><i class="fa fa-info-big volume-code-info"></i>
      </div>
      <div class="paljo-price-container">
        <b><span class="paljo-image-info"><?=$this->transEsc('Cost')?></span></b> <span class="paljo-price"></span>
      </div>
    </div>
    <div class="paljo-create-transaction">
      <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('paljo_pay')?>" name="paljo-pay" />
    </div>
  </form>
</div>

<?php
$js = <<<JS
$(document).ready(function(){
  finna.paljo.initPaljoPrice();
});
JS;
$this->headScript()->appendScript($js);
?>
