<!-- START of: finna - myresearch/paljo-account-creation.phtml -->
<h1><?=$this->transEsc('paljo_id')?></h1>
<div class="infobox">
  <p><?=$this->transEsc('paljo_create_account_info')?></p>
</div>
<form name="paljo-account-creation" method="post" action="<?=$this->url('paljo-account-creation')?>">
  <div>
    <p><b><?=$this->transEsc('Email')?></b></p>
    <input type="text" class="paljo-email" name="email">
    <i class="fa fa-info"></i><span><?=$this->transEsc('paljo_create_account_email_info')?></span>
  </div>
  <div>
    <input type="checkbox" required class="paljo-tos"><?=$this->transEsc('paljo_accept_tos')?>
  </div>
  <input class="btn btn-primary" type="submit" value="<?=$this->transEscAttr('paljo_create_account')?>" />
</form>
<!-- END of: finna - myresearch/paljo-account-creation.phtml -->
