<!-- START of: finna - Auth/Database/loginfields.phtml -->
      <div class="form-group">
        <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Finna Login')?>:</label>
        <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
      </div>
      <div class="form-group">
        <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Finna Password')?>:</label>
        <input type="password" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control"/>
      </div>
      <div class="form-group">
        <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>rememberme"><?=$this->transEsc('Remember me')?>:</label>
        <input type="checkbox" name="rememberme" id="login_<?=$this->escapeHtmlAttr($topClass)?>_rememberme" class="form-control login-remember"/>
      </div>
<!-- END of: finna - Auth/Database/loginfields.phtml -->
