<!-- START of: finna - RecordDriver/DefaultRecord/record-video-player.phtml -->
<?php
  $videoElementBase = [
    'class' => 'videourl fulltext btn btn-primary',
    'type' => 'button'
  ];
  $this->htmlElement()->addAttributeTemplate('video-base', $videoElementBase);
  $videoScripts = $this->partial('Helpers/videojs-urls.phtml');
?>
<div class="video-accordion accordion">
  <?php foreach ($videoUrls as $url): ?>
    <?php
    $embeddedVideo = $this->recordLink()->getEmbeddedVideo($url['url']);
    $desc = $url['desc'] ?? $this->truncateUrl($url['url']);

    if (isset($type) && $type === 'SolrEad') {
      $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $this->translate('link_' . $url['desc'], null, $url['desc']);
    } elseif (isset($type) && $type === 'SolrForward') {
      $desc = $this->translate('default::link_' . $desc, null, $desc);
    } else {
      $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $desc;
    }
    $description = $this->escapeHtml($desc);

    $currentVideo = [
      'data-link' => $this->proxyUrl($url['url']),
      'title' => $url['url'],
    ];

    if (!empty($embeddedVideo)) {
      $currentVideo[$embeddedVideo] = '';
    }

    if (!empty($url['videoSources'])) {
      $currentVideo['data-video-sources'] = json_encode($url['videoSources']);
      $currentVideo['data-scripts'] = $videoScripts;
    }

    if (!empty($url['embed']) && $url['embed'] === 'video') {
      if (isset($this->videoPopup) && $this->videoPopup === false) {
        $currentVideo['data-inline'] = '';
      } else {
        $currentVideo['data-embed-video'] = '';
      }
    }
    ?>
    <div class="video-link-container accordion-toggle <?=$this->htmlElement()->getAttributes($currentVideo);?>">
        <i class="fa fa-play-circle"></i>
        <span class="video-desc"><?=ucfirst($description)?></span>
    </div>
  <?php endforeach; ?>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-video-player.phtml -->
