<!-- START of: finna - search/home.phtml -->
<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
  $this->layout()->introduction = true;
  $this->layout()->ignoreHiddenFilterMemory = true;
?>
<!--  Begin home.phtml and close page container for extra styling  -->
</div>
<div class="container-fluid">
  <div class="container">
    <div>
      <?=($this->ils()->getOfflineMode() == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_home_message']) : ''?>
    </div>
  </div>
</div>
<?php
  $homeTemplate = 'home-page';
  for ($i = 1; $i <= 10; $i++) {
    if ($this->templateSrc("search/home/home-$i")) {
      $homeTemplate = 'home-structured';
      break;
    }
  }
  if ($this->templateSrc("search/home/home-left") || $this->templateSrc("search/home/home-right")) {
    $homeTemplate = 'home-structured';
  }
?>
<div class="container">
  <?=$this->render($this->content()->findTemplateForLng("search/home/$homeTemplate"))?>
</div>
<!-- reopen container -->
<div class="container">
<!-- END of: finna - search/home.phtml -->
