<!-- START of: finna - search/home.phtml -->
<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
  $this->layout()->introduction = true;
  $this->layout()->ignoreHiddenFilterMemory = true;
?>
<!--  Begin home.phtml and close page container for extra styling  -->
</div>
<div class="container-fluid">
  <div class="container">
    <div>
      <?=($this->ils()->getOfflineMode() == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_home_message']) : ''?>
    </div>
  </div>
</div>
<?php if ($this->templateSrc('search/home/home-1')): ?>
<?=$this->render($this->content()->findTemplateForLng("search/home/home-structured"))?>
<?php else: ?>
<?php $homePage = $this->content()->findTemplateForLng("search/home/home-page") ?>
<div class="container">
  <?=$this->render($homePage)?>
</div>
<?php endif; ?>
<!-- reopen container -->
<div class="container">
<!-- END of: finna - search/home.phtml -->
