<?php
$data = $this->driver->getExternalData();
$digitized = $data['digitized'];
$items = $data['items'] ?? [];
$fullResImages = $items['fullResImages'] ?? null;
$ocrImages = $items['OCRImages'] ?? null;
$physicalItems = $items['physicalItems'] ?? null;
$collection = $this->driver->tryMethod('isCollection');
?>
<?php if (!$digitized && !$collection): ?>
  <span><?= $this->translate('external_data_not_digitized') ?></span>
  <div class="external-data-feedback inline"><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Feedback'))?>" data-lightbox class="btn btn-primary"><?=$this->transEsc('Send feedback on record')?></a></div>
<?php else: ?>
  <div class="external-data-feedback"><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Feedback'))?>" data-lightbox class="btn btn-primary"><?=$this->transEsc('external_data_contact_provider')?></a></div>
<?php endif; ?>

<?php if ($fullResImages): ?>
  <?= $this->partial('RecordTab/external_data_table.phtml', ['type' => 'fullres_images', 'data' => $fullResImages]); ?>
<?php endif; ?>

<?php if ($ocrImages): ?>
  <?= $this->partial('RecordTab/external_data_table.phtml', ['type' => 'ocr', 'data' => $ocrImages]); ?>
<?php endif; ?>

<?php if ($physicalItems): ?>

  <div role="table" class="external-data physical-items" aria-label="<?= $this->transEscAttr('external_data_tab_physical_items')?>">
    <div role="row" class="tbl-row headers">
      <div role="cell" class="tbl-cell tbl-left"><span role="columnheader"><?= $this->transEsc('external_data_tab_item_info')?></span></div>
    </div>
  </div>
  <?php $i = 0; ?>
  <?php foreach ($physicalItems as $item): ?>
    <?php $collapsed = $i++ > 0 ? 'collapsed' : ''?>
    <?php $format = $item['format'] ?? $item['original'] ?? $item['type']; ?>

    <div class="external-data-heading external-data physical-items <?=$collapsed?>" role="table">
      <div role="row" class="tbl-row external-data-headers">
        <div role="cell" class="tbl-cell tbl-left"><b class="caret <?=$collapsed?>" aria-hidden="true"></b><span role="columnheader"><?= $this->escapeHtml($format) ?></span>
          <?php if (!empty($item['imageType'])): ?>
            <div class="format-info"><?=$this->transEsc('external_data_tab_image_type')?>: <?=$item['imageType']?></div>
          <?php endif;?>
          <?php if (!empty($item['microfilmCopyType'])): ?>
            <div class="format-info"><?=$this->transEsc('external_data_tab_microfilm_copy_type')?>: <?=$item['microfilmCopyType']?></div>
          <?php endif;?>
        </div>
        <?php if (!empty($item['service'])): ?>
          <div role="cell" class="tbl-cell tbl-right"> <i class="fa fa-ok"></i> <span><?= $this->transEsc('external_data_tab_physical_service')?></span></div>
        <?php else: ?>
          <div role="cell" class="tbl-cell tbl-right"> <i class="fa fa-remove"></i> <span><?= $this->transEsc('external_data_tab_no_service')?></span></div>
        <?php endif; ?>
      </div>
      <?php if (!empty($item['locationInfo'])): ?>
        <div role="row" class="tbl-row">
          <div class="tbl-cell tbl-left" role="cell"><?=$this->transEsc('external_data_tab_location');?></div>
          <div class="tbl-cell tbl-right" role="cell"><?=$item['locationInfo']['location'] ?? ''?></div>
          <div class="tbl-cell tbl-right" role="cell"><?=$item['locationInfo']['locationOffice'] ?? ''?></div>
          <div class="tbl-cell tbl-right" role="cell"><?=$item['locationInfo']['locationType'] ?? ''?></div>
          <div class="tbl-cell tbl-right" role="cell">
            <?php if (!empty($item['locationInfo']['physicalLocation'])): ?><?=$this->transEsc('external_data_tab_location_code') . ': ' . $item['locationInfo']['physicalLocation']?><?php endif; ?>
          </div>
        </div>
      <?php endif; ?>
      <?php if (!empty($item['imageInfo'])): ?>
        <div role="row" class="tbl-row">
          <div class="tbl-cell tbl-left" role="cell"><?= $this->transEsc('external_data_tab_size_info') ?></div>
          <?php if (!empty($item['imageInfo']['imageSize'])): ?>
            <div class="tbl-cell tbl-right" role="cell"><?=$this->transEsc('external_data_tab_image_size')?>: <?=$item['imageInfo']['imageSize']?></div>
          <?php endif; ?>
          <?php if (!empty($item['imageInfo']['imageArea'])): ?>
            <div class="tbl-cell tbl-right" role="cell"><?=$this->transEsc('external_data_tab_image_area')?>: <?=$item['imageInfo']['imageArea']?></div>
          <?php endif; ?>
          <?php if (!empty($item['imageInfo']['mapScale'])): ?>
            <div class="tbl-cell tbl-right" role="cell"><?=$this->transEsc('Scale')?>: <?=$item['imageInfo']['mapScale']?></div>
          <?php endif; ?>
        </div>
      <?php endif; ?>
      <?php if (!empty($item['microfilmSeries'])): ?>
        <div role="row" class="tbl-row">
          <div class="tbl-cell tbl-left" role="cell"><?=$this->transEsc('external_data_tab_microfilm_series')?></div>
          <div class="tbl-cell tbl-right" role="cell"><?=$item['microfilmSeries']?></div>
        </div>
      <?php endif;?>
      <?php if (!empty($item['service'])): ?>
        <div class="tbl-row" role="row">
          <div role="cell" class="tbl-cell tbl-left"><span><?= $this->transEsc('external_data_tab_physical_service_info')?></span></div>
          <?php if (!empty($item['service'])): ?>
            <div role="cell" class="tbl-cell tbl-right"><i class="fa fa-ok"></i> <span><?=$this->transEsc('external_data_tab_physical_service')?></span></div>
          <?php else: ?>
            <div role="cell" class="tbl-cell tbl-right"><i class="fa fa-remove"> </i><span><?=$this->transEsc('external_data_tab_no_service')?></span></div>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<?php
  $this->inlineScript(
      \Laminas\View\Helper\HeadScript::SCRIPT,
      'finna.record.setupExternalDataTab();',
      'SET'
  );
  echo $this->inlineScript();
?>
