<?php
  $images = $item->getAllImages();
  $driver = $this->record($this->item)->getDriver();
  $formats = $driver->tryMethod('getFormats');
  $noImage = empty($images[0]['urls']['medium']);
?>
<div class="similar-carousel-item">
  <div class="similar-carousel-image <?= $noImage ? 'no-image' : ''?>">
    <?php if (!$noImage): ?>
      <img data-src="<?= $images[0]['urls']['medium'] ?? $this->url('cover-unavailable') ?>" />
    <?php else: ?>
    <div class="iconlabel format-<?=$this->record($driver)->getFormatClass(end($formats))?>"></div>
    <?php endif; ?>
  </div>
  <div class="similar-carousel-text">
    <span class="similar-carousel-item-title" title="<?=$this->escapeHtmlAttr($this->item->getTitle())?>"><?=$this->truncate($this->escapeHtml($this->item->getTitle()), 22)?></span>
    <?php $authors = $item->getPrimaryAuthors();
      if (!empty($authors)): ?>
        <span class="similar-carousel-item-author" title="<?=$this->escapeHtmlAttr($authors[0])?>"><?=$this->truncate($this->escapeHtml($authors[0]), 23)?><?php if (count($authors) > 1): ?> <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?></span>
      <?php endif; ?>
    <div>
      <span class="similar-carousel-format"><?=$this->transEsc(end($formats))?></span>
    </div>
  </div>
</div>
