<div class="events-tabs feed-tabs-container feed-tabs">
<h2>Tapahtumat</h2>
  <ul class="nav nav-tabs" role="tablist">
    <?php foreach ($this->tabs as $tab): ?>
      <li class="nav-item event-tab feed-tab" id="<?=$tab['title']?>" data-params="<?=$tab['params']?>"><?= $tab['title'] ?></li>
    <?php endforeach; ?>
  </ul>
  </div>
  <div class="tab-content" id="tab-content-<?=$this->escapeHtmlAttr($this->id)?>">
    <div class="linked-events-content" data-init="0"></div>
  </div>
<?php
$this->headScript()->appendFile("finna-linked-events.js");
$js = <<<JS
$(document).ready(function(){
  finna.linkedEvents.initEventsTabs();
});
JS;
$this->headScript()->appendScript($js);
?>