<!-- START of: finna - Helpers/linkedeventstabs.phtml -->
<div class="events-tabs feed-tabs-container feed-tabs" data-tabs="<?= $this->escapeHtmlAttr(json_encode($this->tabs)); ?>">
  <h2><?= $this->transEsc('Events'); ?></h2>
  <ul class="nav nav-tabs" role="tablist">
    <?php foreach ($this->tabs as $id => $tab): ?>
      <?php $isActive = $this->active === $tab['title'] ?>
      <li class="nav-item event-tab feed-tab <?= $isActive ? 'active' : ''; ?>" id="<?=$tab['title']?>"
        tabindex="0"
        aria-selected="<?= $isActive ? 'true' : 'false'; ?>"
        data-params="<?= isset($tab['params']) ? $this->escapeHtmlAttr(json_encode($tab['params'])) : ''?>"
        aria-label="<?= $tab['title']; ?>"
        ><?= $tab['title'] ?></li>
    <?php endforeach; ?>
  </ul>
  </div>
  <?php if ($this->searchTools !== 'hide'): ?>
  <?php if ($this->searchTools === 'button'): ?>
    <button class="btn btn-primary events-toggle-searchtools">Näytä hakutoiminnot</button>
    <button class="btn btn-primary events-toggle-searchtools hidden">Piilota hakutoiminnot</button>
  <?php endif; ?>
  <div class="events-searchtools-container <?= $this->searchTools === 'show' ? '' : 'hidden'; ?>">
    <span class="event-search-container">
      <input id="event-text-search" type="text" placeholder="<?= $this->transEsc('Tapahtuman nimi tai paikka') ?>" size="26">
    </span>
    <button class="btn btn-primary linked-event-search"><?= $this->transEsc('Find') ?></button>
    <span class="event-date-container">
      <?= $this->transEsc('Etsi vain ajalta'); ?>:
      <input id="event-date-start" type="date"> &ndash; <input id="event-date-end" type="date">
    </span>
    <span class="event-geolocation-container">
      <span class="event-geolocation"><?= $this->transEsc('use_my_location'); ?></span>
    </span>
  </div>
<?php endif; ?>
  <div class="tab-content">
    <div class="linked-events-content"></div>
  </div>
  <button class="btn btn-primary linked-events-next"><?= $this->transEsc('Näytä lisää') ?></button>
  <a class="btn btn-primary events-more-link <?= $this->moreLink ? '' : 'hidden' ?>" href="<?= $this->moreLink; ?>"><?= $this->transEsc('Näytä kaikki tapahtumat') ?></a>
<?php
$this->headScript()->appendFile("finna-linked-events.js");
$js = <<<JS
$(document).ready(function(){
  finna.linkedEvents.initEventsTabs("{$this->active}");
});
JS;
$this->headScript()->appendScript($js);
?>
<!-- END of: finna - Helpers/linkedeventstabs.phtml -->
