<!-- START of: finna - Helpers/linkedeventstabs.phtml -->
<div class="linked-events-tabs-container" id="<?= $this->id ?>">
  <div class="events-tabs feed-tabs-container feed-tabs" data-tabs="<?= $this->escapeHtmlAttr(json_encode($this->tabs)); ?>">
    <h2><?= $this->transEsc('Events'); ?></h2>
    <ul class="nav nav-tabs" role="tablist">
      <?php foreach ($this->tabs as $id => $tab): ?>
        <?php $isActive = $this->active === $tab['title'] ?>
        <li class="nav-item event-tab feed-tab <?= $isActive ? 'active' : ''; ?>" id="<?=$tab['title']?>"
          tabindex="0"
          aria-selected="<?= $isActive ? 'true' : 'false'; ?>"
          data-params="<?= isset($tab['params']) ? $this->escapeHtmlAttr(json_encode($tab['params'])) : ''?>"
          aria-label="<?= $tab['title']; ?>"
          ><?= $tab['title'] ?></li>
      <?php endforeach; ?>
    </ul>
  </div>

  <div class="feed-accordions event-accordions" role="tablist">
    <h2 class="feed-accordions-title event-accordions-title"><?= $this->transEsc('Events'); ?></h2>
    <?php $i = 0; foreach ($this->tabs as $id => $tab): ?>
      <?php
        $classes = ['accordion', 'accordion-' . $tab['title']];
        $isActive = 0 === strcasecmp($this->active, $tab['title']);
        if ($isActive) {
          $classes[] = 'active initial-active';
        }
      ?>
      <div class="<?=$this->escapeHtmlAttr(implode(' ', $classes))?>"
           data-params="<?=$this->escapeHtmlAttr(json_encode($tab['params']))?>"
           data-title="<?=$tab['title']?>"
           role="tab"
           tabindex="0"
           aria-selected="<?= $isActive ? 'true' : 'false' ?>">
          <span class="title"><?=$this->transEsc($tab['title'])?></span>
          <i class="icon"></i>
      </div>
    <?php endforeach; ?>
  </div>
  <?php if ($this->searchTools !== 'hide'): ?>
    <div class="events-searchtools-toggle"><?= $this->transEsc('Näytä rajaimet') ?> <i class="fa fa-arrow-down"></i></div>
    <div class="events-searchtools-container <?= $this->searchTools === 'show' ? '' : 'hidden'; ?>">
      <span class="event-search-container">
        <input class="event-text-search" type="text" placeholder="<?= $this->transEsc('Tapahtuman nimi tai paikka') ?>" size="26">
      </span>
      <span class="event-date-container">
        <span class="event-date-title"><?= $this->transEsc('Etsi vain ajalta'); ?>:</span>
        <input class="event-date-start event-datepicker"> &ndash; <input class="event-date-end event-datepicker">
      </span>
      <button class="btn btn-primary linked-event-search"><?= $this->transEsc('Find') ?></button>
      <span class="event-geolocation-container hidden">
        <span class="event-geolocation"><?= $this->transEsc('use_my_location'); ?></span>
      </span>
    </div>
  <?php endif; ?>
  <div class="tab-content">
    <div class="linked-events-content"></div>
  </div>
  <div class="linked-events-buttons">
    <button class="btn btn-outline-primary linked-events-next"><?= $this->transEsc('Näytä lisää') ?></button>
    <a class="btn btn-outline-primary events-more-link <?= $this->moreLink ? '' : 'hidden' ?>" href="<?= $this->moreLink; ?>"><?= $this->transEsc('Näytä kaikki tapahtumat') ?></a>
  </div>
</div>
<?php
$this->headScript()->appendFile("finna-linked-events.js");
$this->jsTranslations()->addStrings(
  [
    'nohit_heading' => 'nohit_heading',
  ]);
$translations = $this->jsTranslations()->getJSON();
$js = <<<JS
$(document).ready(function(){
  finna.linkedEvents.initEventsTabs("{$this->id}");
  VuFind.addTranslations({$translations});
});
JS;
$this->headScript()->appendScript($js);
?>
<!-- END of: finna - Helpers/linkedeventstabs.phtml -->
