<!-- START of: finna - ajax/feed-grid.phtml -->
<div class="feed-grid<?= $this->images ? ' with-image' : ''; ?>">
  <?php
    $itemCount = 0;
  ?>
  <?php foreach($items as $item): ?>
    <?php
      $linkElement = [
      'href' => $item['link'],
      ];
      if ($this->linkTarget) {
        $linkElement['target'] = $this->linkTarget;
      }
      if ($item['modal']) {
        $linkElement['data-lightbox'] = '';
        $linkElement['data-lightbox-title'] = $item['title'];
      }
    ?>
    <div class="grid-item <?= isset($this->visualItems) ? ($itemCount++ >= $this->visualItems ? 'hidden truncate' : '') : ''; ?> ">
      <a class="grid-link" <?= $this->htmlElement()->getAttributes($linkElement);?>>
        <?php if (isset($item['image']) && isset($item['image']['url'])): ?>
          <span class="grid-image">
            <img src="<?= $item['image']['url']; ?>" alt="" />
          </span>
        <?php endif; ?>
        <span class="grid-info">
          <?php if (isset($item['dateFull'])): ?>
            <div><?= $item['dateFull'] ?></div>
          <?php endif; ?>
          <div class="title"><?= $this->truncate($item['title'], 40); ?></div>
          <?php if (isset($item['text'])): ?>
            <div class="feed-text"><?= $this->truncate($item['text'], 80); ?></div>
          <?php endif; ?>
        </span>
      </a>
    </div>
  <?php endforeach; ?>
</div>
<button class="btn btn-primary show-more-feeds hidden"><?= $this->translate('show_more') ?></button>
<button class="btn btn-primary show-less-feeds hidden"><?= $this->translate('show_less') ?></button>
<!-- END of: finna - ajax/feed-grid.phtml -->
