<!-- START of: finna - ajax/linked-events.phtml -->
<div class="linked-events feed-grid with-image">
  <?php $i = 0 ?>
  <?php foreach ($this->events as $event): ?>
    <?php if (isset($this->limit) && $i++ === $this->limit): break; endif; ?>
    <div class="linked-event grid-item">
    <?php if (isset($event['link'])): ?><a class="grid-link" href="<?= $this->escapeHtmlAttr($event['link']) ?>"><?php endif; ?>
      <span class="linked-events-image grid-image <?= !empty($event['imageurl']) ? '' : 'no-image' ?>">
        <?php if (!empty($event['imageurl'])): ?>
          <img src=<?= $this->escapeHtmlAttr($event['imageurl']) ?>>
        <?php else: ?>
          <i class="fa fa-calendar-o image-placeholder"></i>
        <?php endif; ?>
      </span>
      <span class="grid-info">
        <?php if (isset($event['name'])): ?>
          <span class="event-info"><b><?= $this->truncate($event['name'], 30) ?></b></span>
        <?php endif; ?>
        <?php if (isset($event['startDate'])): ?>
          <p class="event-info"><i class="fa fa-calendar"></i> <?= $event['startDate']; ?> <?php if (isset($event['endDate']) && $event['startDate'] !== $event['endDate']):?>&nbsp;&ndash;&nbsp;<?= $event['endDate']?><?php endif; ?></p>
        <?php endif; ?>
        <?php if (isset($event['startTime']) && isset($event['endDate']) && $event['startDate'] === $event['endDate']): ?>
          <p class="event-info"> <i class="fa fa-clock-o"></i> <?= $event['startTime']; ?><?php if (isset($event['endTime'])): ?>&nbsp;&ndash;&nbsp;<?=$event['endTime'];?><?php endif; ?></p>
        <?php endif; ?>
        <?php if (isset($event['location']) && $event['location']): ?>
          <p class="event-info"><i class="fa fa-map-marker"></i> <?= $event['location']; ?></p>
        <?php endif; ?>
        <?php if (isset($event['short_description'])): ?>
          <p class="event-info"><?= $this->truncate($event['short_description'], 60) ?></p>
        <?php endif; ?>
      </span>
    <?php if (isset($event['link'])): ?></a><?php endif; ?>
    </div>
  <?php endforeach; ?>
</div>
<!-- END of: finna - ajax/linked-events.phtml -->
