<!-- START of: finna - ajax/linked-events.phtml -->
<div class="linked-events feed-grid with-image">
  <?php foreach ($this->events as $event): ?>
  <?php
      $linkElement = [
      'href' => $event['link'],
      ];
      if ($this->linkTarget) {
        $linkElement['target'] = '';
      }
      $linkElement['data-lightbox'] = '';
    ?>
    <div class="linked-event grid-item">
    <?php if (isset($event['link'])): ?><a class="grid-link" <?= $this->htmlElement()->getAttributes($linkElement)?>><?php endif; ?>
      <?php if (isset($event['imageurl'])): ?>
        <span class="linked-events-image grid-image">
          <img src=<?= $event['imageurl'] ?>>
        </span>
      <?php endif; ?>
      <span class="grid-info">
        <?php if (isset($event['name'])): ?>
          <span class="event-info"><b><?= $this->truncate($event['name'], 30) ?></b></span>
        <?php endif; ?>
        <?php if (isset($event['startDate'])): ?>
          <p class="event-info"><i class="fa fa-calendar"></i> <?= $event['startDate']; ?> <?php if (isset($event['end_date']) && $event['startDate'] !== $event['endDate']):?>&nbsp;&ndash;&nbsp;<?= $event['endDate']?><?php endif; ?></p>
        <?php endif; ?>
        <?php if (isset($event['startTime'])): ?>
          <p class="event-info"> <i class="fa fa-clock-o"></i> <?= $event['startTime']; ?><?php if (isset($event['endTime'])): ?>&nbsp;&ndash;&nbsp;<?=$event['endTime'];?><?php endif; ?></p>
        <?php endif; ?>
        <?php if (isset($event['location']) && $event['location']): ?>
          <p class="event-info"><i class="fa fa-map-marker"></i> <?= $event['location']; ?></p>
        <?php endif; ?>
        <?php if (isset($event['short_description'])): ?>
          <p class="event-info"><?= $this->truncate($event['short_description'], 60) ?></p>
        <?php endif; ?>
      </span>
    <?php if (isset($event['link'])): ?></a><?php endif; ?>
    </div>
  <?php endforeach; ?>
</div>
<div class="linked-events-pagination">
  <span class="linked-events-previous <?= $this->previous ? '' : 'hidden' ?>" data-previous="<?= !empty($this->previous) ? $this->previous : false ?>"><i class="fa fa-arrow-left"></i></span>
  <span class="linked-events-next <?= $this->next ? '' : 'hidden' ?>" data-next="<?= !empty($this->next) ? $this->next : false ?>"><i class="fa fa-arrow-right"></i></span>
</div>
<!-- END of: finna - ajax/linked-events.phtml -->
