<h2 class="lightbox-header"><?=$this->transEsc('Tilit, joihin kortti on liitetty'); ?></h2>
<table class="table table-striped">
<tr><th>Liittämispäivä</th><th><?=$this->transEsc('Institution')?></th><th><?=$this->transEsc('account_login_method')?></th></tr>
<?php foreach ($this->users as $user): ?>
    <?php $institution = explode(':', $user->cat_id);
        $parts = explode('.', $institution[0]);
        $org = $parts[0];
    ?>
    <tr>
    <td><?= $user->created?></td>
    <td><?= $org?></td>
    <td><?= $this->transEsc('login_method_' . $user->auth_method) ?></td>
    </tr>
    <?=$user->username?>
<?php endforeach; ?>
</table>