<!-- START of: finna - myresearch/controls/paljo-limit.phtml -->
<?php
  $currentLimit = $this->limit ?? 50;
  $limits = [1, 2, 50];
  $limitList = [];
  foreach ($limits as $lim) {
    $limitList[$lim] = [
      'desc' => $lim,
      'selected' => $currentLimit == $lim
    ];
  }
?>
<?php if (count($limitList) > 1): ?>
<div class="limit-option-container">
  <span class="hidden-sm hidden-xs hidden-md button-label" id="limit-label"><?=$this->transEsc('Results per page')?></span>
  <span class="sr-only hidden-lg hidden-md"><?=$this->transEsc('Results per page')?></span>
  <div class="sort-button">
    <div class="dropdown">
      <?php foreach ($limitList as $limitVal => $limitData): ?>
        <?php if ($limitData['selected']): ?>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-label="<?=$this->transEsc('Results per page') . ': ' . $this->transEsc($limitData['desc'])?>">
          <span><?=$this->transEsc($limitData['desc'])?></span> <i class="fa fa-arrow-down"></i>
        </a>
        <?php endif; ?>
      <?php endforeach; ?>
      <ul class="dropdown-menu" role="menu" aria-labelledby="limit-label">
        <?php foreach ($limitList as $limitVal => $limitData): ?>
        <li>
          <a href="<?=$this->url('paljo-subscriptions')?>?limit=<?=$limitData['desc']?>&show=<?=$this->show?>" role="menuitem" aria-label="<?=$this->transEsc('Results per page') . ': ' . $this->transEsc($limitData['desc'])?>"><?=$this->transEsc($limitData['desc'])?></a>
        <?php endforeach; ?>
        </li>
      </ul>
      <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
    </div>
  </div>
</div>
<?php endif; ?>
<!-- END of: finna - myresearch/controls/paljo-limit.phtml -->
