<?php
  $user = $this->auth()->isLoggedIn();
  $imageSize = $this->driver->tryMethod('getPaljoImageSize');
  $images = $this->driver->getAllImages();
?>
<h1><?=$this->transEsc('paljo_image_subscription')?> <i class="fa fa-info-big"></i></h1>
<div class="infobox"><?=$this->transEsc('paljo_image_subscription_info')?></div>
<div><?=$this->transEsc('paljo_user_email')?> <b><span class="paljo-user-email"><?=$user->paljo_id?></span></b></div>
<form id="paljo-form" action="<?=$this->url('paljo-create-subscription')?>" method="post">
  <div class="paljo-sub-container">
    <div class="paljo-image">
      <img src="<?= $images[0]['urls']['medium'] ?? '' ?>" />
    </div>
    <div class="paljo-image-info-container">
      <h2><a href="<?=$this->url('record', ['id' => $this->recordId])?>"><?=$this->driver->getFullTitle()?></a></h2>
      <div class="paljo-flex">
        <input type="hidden" name="image-id" value="<?=$this->id?>" />
        <input type="hidden" name="record-id" value="<?=$this->recordId?>" />
        <span class="paljo-image-info"><b><?=$this->transEsc('paljo_image_id')?></b></span> <span><?=$this->id?></span>
      </div>
      <div class="paljo-flex">
        <span class="paljo-image-info"><b><?=$this->transEsc('paljo_price_type')?></b></span>
        <select class="paljo-price-type-menu" id="paljo-price-menu" name="price-type">
          <?php foreach ($this->prices as $price): ?>
            <option class="paljo-price-type" value="<?= $this->escapeHtmlAttr($price['license'])?>" data-price="<?=$this->escapeHtmlAttr($price['price'])?>" data-license="<?=$this->escapeHtmlAttr($price['license'])?>" data-license-desc=""><?=$price['license']?></option>
          <?php endforeach; ?>
        </select>
      </div>
      <?php if (!empty($imageSize)): ?>
        <div class="paljo-flex">
          <span class="paljo-image-info"><b><?=$this->transEsc('paljo_size')?></b></span>
            <input type="hidden" name="image-size" value="<?=$imageSize['height']['value']?>x<?=$imageSize['width']['value']?>">
            <?=$imageSize['height']['value']?> * <?=$imageSize['width']['value']?> <?=$imageSize['width']['unit']?>
        </div>
      <?php endif; ?>
      <div class="paljo-flex">
        <span class="paljo-image-info"><b><?=$this->transEsc('paljo_license')?>: </b></span> <span class="paljo-image-license"></span>
      </div>
      <div class="paljo-flex">
        <span class="paljo-image-info"><b><?=$this->transEsc('paljo_additional_information')?></b></span>
        <textarea class="paljo-additional-info" type="text" name="user-message" rows="3" cols="20"></textarea>
      </div>
      <input type="hidden" name="organisationId" value="<?=$this->organisationId?>">
      <div class="paljo-flex">
        <span class="paljo-image-info"><b><?=$this->transEsc('paljo_volume_code')?></b></span>
        <span class="paljo-code-input">
          <span>
          <input list="volume-codes" type="text" name="volume-code" class="paljo-volume-code" placeholder="<?=$this->escapeHtmlAttr($this->translate('Input'))?>"><button class="discount btn btn-primary"> hae alennus</button><i class="fa fa-info-big volume-code-info"></i>
          <?php if (isset($this->volumeCodes)): ?>
            <datalist id="volume-codes">
            <?php foreach ($this->volumeCodes as $code): ?>
              <?php if ($code->organisation_id === $this->organisationId): ?>
                <option value="<?=$code->volume_code?>"><?=$this->transEsc('paljo_discount')?>: <?=$code->discount?> %</option>
              <?php endif; ?>
            <?php endforeach; ?>
          <?php endif; ?>
          </span>
        </span>
      </div>
      <div class="paljo-flex">
        <span class="paljo-image-info"><b><?=$this->transEsc('Cost')?></b></span> <span class="paljo-price"></span>
      </div>
    </div>
  </div>
  <div class="paljo-create-transaction">
    <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('paljo_pay')?>" name="paljo-pay" />
    <a href="<?=$this->url('record', ['id' => $this->recordId]);?>"><?=$this->transEsc('paljo_cancel_order')?></a>
  </div>
</form>
<?php
$js = <<<JS
$(document).ready(function(){
  finna.paljo.initPaljoPrice();
});
JS;
$this->headScript()->appendScript($js);
?>
