<!-- START of: finna - Related/Similar-carousel.phtml -->
<?php $similarRecords = $this->related->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
  <div class="similar-carousel">
    <finna-feed class="splide">
      <h2 class="similar-carousel-header"><?=$this->transEsc('Similar Items')?></h2>
      <div class="similar-carousel-container">
        <div class="splide__arrows splide__arrows--ltr">
          <button class="splide__arrow splide__arrow--prev left">
            <?=$this->icon('chevron-right')?>
          </button>
          <button class="splide__arrow splide__arrow--next right">
            <?=$this->icon('chevron-right')?>
          </button>
        </div>
        <div class="splide__track carousel">
          <ul class="splide__list carousel-feed">
            <?php foreach ($similarRecords as $item): ?>
              <li class="splide__slide similar-item-holder">
                  <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($item))?>">
                    <?=$this->partial('Related/similar-carousel-item.phtml', compact('item'))?>
                  </a>
              </li>
            <?php endforeach; ?>
          </ul>
        </div>
      </div>
      <div class="carousel-pagination-wrapper">
        <div class="carousel-autoplay"></div>
        <ul class="splide__pagination"></ul>
        <div class="carousel-block"></div>
      </div>
   </finna-feed>
  </div>
<?php else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<?php endif; ?>
<!-- END of: finna - Related/Similar-carousel.phtml -->
