<?php
  $images = $item->getAllImages();
  $driver = $this->record($this->item)->getDriver();
  $formats = $driver->tryMethod('getFormats');
  $noImage = empty($images[0]['urls']['medium']);
?>
<div class="similar-carousel-item">
  <div class="similar-carousel-image <?= $noImage ? 'no-image' : ''?>">
    <?php if (!$noImage): ?>
      <img data-src="<?= $images[0]['urls']['medium'] ?? $this->url('cover-unavailable') ?>" />
    <?php else: ?>
    <div class="iconlabel format-<?=$this->record($driver)->getFormatClass(end($formats))?>"></div>
    <?php endif; ?>
  </div>
  <div class="similar-carousel-text">
    <b><?=$this->truncate($this->escapeHtml($this->item->getTitle()), 70)?></b>
    <?php $authors = $item->getPrimaryAuthors();
      if (!empty($authors)): ?>
        <br><?=$this->escapeHtml($authors[0]);?><?php if (count($authors) > 1): ?> <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?>
      <?php endif; ?>
    <div>
      <span class="similar-carousel-format"><?=$this->transEsc(end($formats))?></span>
    </div>
  </div>
</div>
