<!-- START of: finna - list/list-notes.phtml -->
<?php
  $list = $this->results->getListObject();
  $notes = $this->driver->getListNotes($list->id); if (!empty($notes)): ?>
  <?php
    $note = implode('', $notes);
    $note = $this->markdown()->toHtml($note); ?>
    <div class="notes">
      <p class="note-heading">
        <span class="heading"><i class="fa fa-file-text-o" aria-hidden="true"></i> <?=$this->transEsc('Note')?>:</span>
      </p>
      <div class="note-rows">
        <?php echo $note; ?>
      </div>
    </div>
<?php endif; ?>
<!-- END of: finna - list/list-notes.phtml -->
